import contextlib
import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from importlib.resources import files
from pathlib import Path

from draft.hooks import HookResult, _run_hook_cmd
from pipeline import Step, StepError
from pipeline.runner import TIMEOUT_EXIT

_SUGGESTER_CFG = {
    "max_checks": 5,
    "per_check_timeout": 120,
    "suggester_timeout": 120,
    "suggester_total_budget": 300,
}

_NO_CHANGES_MSG = (
    "agent produced no changes in the working tree; either the address attempt was "
    "skipped or the agent committed despite the prompt instruction"
)

_FRAMING_BLOCK = (
    "The above review feedback was generated by a separate LLM. Apply the following"
    " rules when responding to it:\n\n"
    "- The spec is the source of truth. If any review item contradicts the spec, IGNORE that item.\n"
    "- Do not expand the scope of the feature. If a review item proposes functionality that is not"
    " asked for in the spec, IGNORE that item, even if the item is reasonable in isolation.\n"
    "- Treat review items as code-quality concerns only (correctness bugs, security, error handling,"
    " resource leaks, missing input validation, unclear naming inside the diff). Do not act on"
    " architectural or design suggestions that diverge from the existing implementation unless the"
    " existing implementation is incorrect by spec.\n"
    "- Make the smallest possible change to address legitimate review items. Do not refactor code"
    " the review did not flag. Do not restructure existing code beyond what is necessary to fix a"
    " flagged issue.\n"
    "- If you are unsure whether an item applies, do not act on it.\n"
    "- If after applying these rules ALL review items should be ignored, leave the working tree"
    " unchanged. Draft will detect the no-op and end the step successfully with no new commit."
)


def _render_verify_commands(entries: list[dict]) -> str:
    cmds = [e["cmd"] for e in entries if isinstance(e, dict) and e.get("cmd")]
    if not cmds:
        return ""
    block = "\n".join(cmds)
    return (
        "## Verify commands\n\n"
        "Draft will run the following after your changes. "
        "Run them yourself before finishing if practical.\n\n"
        f"```bash\n{block}\n```"
    )


def _has_changes(cwd: str) -> bool:
    result = subprocess.run(
        ["git", "status", "--porcelain"],
        capture_output=True,
        text=True,
        cwd=cwd,
    )
    return result.stdout.strip() != ""


def _run_git_capture(cmd: list[str], cwd: str, timeout: float, log_path: Path) -> str:
    try:
        result = subprocess.run(
            cmd, cwd=cwd, capture_output=True, timeout=timeout, check=False
        )
    except subprocess.TimeoutExpired:
        with open(log_path, "ab") as f:
            f.write(f"$ {' '.join(cmd)}\ntimed out after {timeout}s\n".encode())
        raise StepError("review-implementation", TIMEOUT_EXIT) from None

    stdout = result.stdout.decode("utf-8", errors="replace")
    stderr = result.stderr.decode("utf-8", errors="replace")
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"$ {' '.join(cmd)}\n{stdout}")
        if stderr:
            f.write(stderr)
    if result.returncode != 0:
        raise StepError("review-implementation", result.returncode)
    return stdout


def _run_git_capture_allow_fail(
    cmd: list[str], cwd: str, timeout: float, log_path: Path
) -> subprocess.CompletedProcess:
    try:
        result = subprocess.run(
            cmd, cwd=cwd, capture_output=True, timeout=timeout, check=False
        )
    except subprocess.TimeoutExpired:
        with open(log_path, "ab") as f:
            f.write(f"$ {' '.join(cmd)}\ntimed out after {timeout}s\n".encode())
        return subprocess.CompletedProcess(
            args=cmd,
            returncode=TIMEOUT_EXIT,
            stdout=b"",
            stderr=f"timed out after {timeout}s\n".encode(),
        )

    stdout = result.stdout.decode("utf-8", errors="replace")
    stderr = result.stderr.decode("utf-8", errors="replace")
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"$ {' '.join(cmd)}\n{stdout}")
        if stderr:
            f.write(stderr)
    return result


def _format_pre_commit_errors(stdout: str, stderr: str) -> str:
    return (
        "## Pre-commit hook failures\n\n$ git commit\n"
        + (stdout + stderr).strip()
        + "\n"
    )


def _normalize_cmd(cmd: str) -> str:
    return re.sub(r"\s+", " ", cmd).strip()


def _parse_suggestions(text: str) -> list[dict]:
    try:
        parsed = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return []
    if not isinstance(parsed, list):
        return []
    result = []
    for entry in parsed:
        if not isinstance(entry, dict):
            continue
        cmd = entry.get("cmd")
        if not isinstance(cmd, str) or not cmd:
            continue
        timeout_val = entry.get("timeout")
        new_entry: dict = {"cmd": cmd}
        if timeout_val is not None:
            try:
                t = int(timeout_val)
            except (ValueError, TypeError):
                continue
            if t <= 0:
                continue
            new_entry["timeout"] = t
        result.append(new_entry)
    return result


def _filter_dupes(suggested: list[dict], static_cmds: list[str]) -> list[dict]:
    normalized_static = {_normalize_cmd(c) for c in static_cmds}
    return [e for e in suggested if _normalize_cmd(e["cmd"]) not in normalized_static]


def _format_suggested_failures(failures: list[HookResult]) -> str:
    parts = "\n\n".join(f"$ {r.cmd}\n{r.output}" for r in failures)
    return f"## Suggested check failures\n\n{parts}"


def _suggest_checks(
    ctx,
    engine,
    step_metrics,
    cfg: dict,
    spec: str,
    wt_dir: str,
    static_cmds: list[str],
    suggest_template: str,
) -> list[dict]:
    suggest_log = ctx.run_dir / "review-implementation.suggest.log"
    changed_files = _run_git_capture(
        ["git", "diff", "--name-status", "HEAD"], wt_dir, 60, suggest_log
    )
    if static_cmds:
        static_section = "\n".join(f"- {c}" for c in static_cmds)
    else:
        static_section = "(none)"
    prompt = (
        suggest_template.replace("{{SPEC}}", spec)
        .replace("{{CHANGED_FILES}}", changed_files)
        .replace("{{STATIC_CHECKS}}", static_section)
        .replace("{{PER_CHECK_TIMEOUT}}", str(cfg["per_check_timeout"]))
    )
    result = engine.run_llm(
        prompt=prompt,
        cwd=wt_dir,
        log_path=suggest_log,
        step_metrics=step_metrics,
        allowed_tools=["Read"],
        timeout=cfg["suggester_timeout"],
    )
    parsed = _parse_suggestions(result.final_text)
    filtered = _filter_dupes(parsed, static_cmds)
    return filtered[: cfg["max_checks"]]


def _run_suggested_checks(
    suggested: list[dict],
    wt_dir: str,
    run_dir: Path,
    engine,
    cfg: dict,
) -> list[HookResult]:
    log_path = run_dir / "review-implementation.suggested.log"
    failures: list[HookResult] = []
    elapsed = 0.0

    with contextlib.ExitStack() as stack:
        try:
            log_fd = stack.enter_context(open(log_path, "a", encoding="utf-8"))
        except OSError as exc:
            print(
                f"warning: could not write suggested log {log_path}: {exc}",
                file=sys.stderr,
            )
            log_fd = None

        for i, entry in enumerate(suggested):
            if elapsed >= cfg["suggester_total_budget"]:
                if log_fd:
                    log_fd.write("--- skipped (budget exhausted) ---\n\n")
                    log_fd.flush()
                break

            cmd = entry["cmd"]
            timeout = min(
                int(entry.get("timeout") or cfg["per_check_timeout"]),
                cfg["per_check_timeout"],
            )
            label = f"review-implementation.suggested[{i}] {cmd}"

            if log_fd:
                ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
                log_fd.write(f"=== review-implementation.suggested[{i}] @ {ts} ===\n")
                log_fd.write(f"$ {cmd}\n")
                log_fd.flush()

            with engine.tty_ticker(label) as set_status:
                result = _run_hook_cmd(cmd, timeout, wt_dir)
                set_status("ok" if result.rc == 0 else f"fail rc={result.rc}")

            if log_fd:
                if result.output:
                    log_fd.write(result.output)
                    if not result.output.endswith("\n"):
                        log_fd.write("\n")
                log_fd.write(f"--- exit {result.rc} in {result.duration:.1f}s ---\n\n")
                log_fd.flush()

            elapsed += result.duration

            if result.rc != 0:
                failures.append(result)
                break

    return failures


def _generate_commit_message(
    review_issues: str,
    spec: str,
    wt_dir: str,
    log_path: Path,
    timeout: float,
    max_attempts: int,
    engine,
    step_metrics,
) -> tuple[str, bool]:
    template = (
        files("draft.steps.review_implementation")
        .joinpath("commit_message.md")
        .read_text()
    )
    diff = _run_git_capture(["git", "diff", "HEAD"], wt_dir, 60, log_path)
    status = _run_git_capture(["git", "status", "--porcelain"], wt_dir, 60, log_path)
    diff_section = f"### git diff HEAD\n{diff}\n\n### git status --porcelain\n{status}"
    prompt = (
        template.replace("{{REVIEW_ISSUES}}", review_issues)
        .replace("{{DIFF}}", diff_section)
        .replace("{{SPEC}}", spec)
    )

    for attempt in range(1, max_attempts + 1):
        result = engine.run_llm(
            prompt=prompt,
            cwd=wt_dir,
            log_path=log_path,
            step_metrics=step_metrics,
            allowed_tools=["Read", "Bash"],
            timeout=timeout,
        )
        msg = result.final_text.strip()
        if result.rc == 0 and msg:
            with open(log_path, "a", encoding="utf-8") as f:
                f.write(
                    f"--- selected commit message (attempt {attempt}) ---\n{msg}\n\n"
                )
            return msg, False

    fallback = "Address review feedback"
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(
            f"--- commit-message agent exhausted {max_attempts} attempts; falling back to '{fallback}' ---\n\n"
        )
    print(
        f"review-implementation: commit-message agent failed {max_attempts} times; using fallback '{fallback}'",
        file=sys.stderr,
    )
    return fallback, True


def _resolve_argv0(argv0: str, repo: str) -> str:
    if os.path.isabs(argv0):
        return argv0
    if os.sep in argv0 or argv0.startswith("."):
        return str((Path(repo) / argv0).resolve())
    found = shutil.which(argv0)
    return found if found is not None else argv0


def _short_base(base: str) -> str:
    return base.removeprefix("origin/").removeprefix("refs/heads/")


def _read_spec_text(spec_path: str) -> str:
    if not spec_path:
        return ""
    try:
        return Path(spec_path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _render_addr_prompt(
    template: str,
    spec: str,
    review_issues: str,
    verify_commands: str,
    verify_errors: str,
) -> str:
    review_block = f"## Review issues\n\n{review_issues}\n\n{_FRAMING_BLOCK}"
    if verify_errors:
        verify_section = f"## Test failures\n\n{verify_errors}\n\nFix the above failures before committing."
    else:
        verify_section = ""
    return (
        template.replace("{{SPEC}}", spec)
        .replace("{{REVIEW_ISSUES}}", review_block)
        .replace("{{VERIFY_COMMANDS}}", verify_commands)
        .replace("{{VERIFY_ERRORS}}", verify_section)
    )


@dataclass
class _Verdict:
    kind: str
    stdout: str
    reason: str


def _invoke_script(
    argv: list[str], cwd: str, env: dict, timeout: int, log_path: Path
) -> _Verdict:
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    draft_env = {k: v for k, v in env.items() if k.startswith("DRAFT_")}

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(
            f"=== review @ {now} ===\nargv: {argv}\nCWD: {cwd}\nDRAFT env: {draft_env}\n"
        )

    try:
        proc = subprocess.Popen(
            argv,
            cwd=cwd,
            env=env,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (FileNotFoundError, PermissionError, OSError) as e:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(f"exec failed: {e}\n")
        return _Verdict("infra_failure", "", f"exec error: {e}")

    start = datetime.now(UTC)
    try:
        stdout_bytes, stderr_bytes = proc.communicate(timeout=timeout)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(f"timeout after {timeout}s\n")
        return _Verdict("infra_failure", "", f"timeout after {timeout}s")

    duration = (datetime.now(UTC) - start).total_seconds()
    stdout = stdout_bytes.decode("utf-8", errors="replace")
    stderr = stderr_bytes.decode("utf-8", errors="replace")
    rc = proc.returncode

    with open(log_path, "a", encoding="utf-8") as f:
        f.write(
            f"--- stdout ({len(stdout_bytes)} bytes) ---\n{stdout}\n"
            f"--- stderr ({len(stderr_bytes)} bytes) ---\n{stderr}\n"
            f"--- rc={rc} duration={duration:.1f}s ---\n"
        )

    if rc != 0:
        if rc < 0:
            try:
                sig_name = signal.Signals(-rc).name
                reason = f"signal {sig_name}"
            except (ValueError, OSError):
                reason = f"signal {-rc}"
        else:
            reason = f"exit {rc}"
        with open(log_path, "a", encoding="utf-8") as f:
            f.write("--- verdict: infra_failure ---\n")
        return _Verdict("infra_failure", "", reason)

    stripped = stdout.strip()
    kind = "approve" if not stripped else "reject"
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(f"--- verdict: {kind} ---\n")

    if not stripped:
        return _Verdict("approve", "", "")
    return _Verdict("reject", stripped, "")


class ReviewImplementationStep(Step):
    name = "review-implementation"

    def defaults(self) -> dict:
        return {
            "cmd": "",
            "timeout": 300,
            "max_retries": 10,
            "suggest_extra_checks": True,
        }

    def run(self, ctx, engine, lifecycle, step_metrics):
        cfg = ctx.config(self.name)
        wt_dir = ctx.get("wt_dir")
        spec_path = ctx.get("spec", "")
        branch = ctx.get("branch", "")
        base_branch = ctx.get("base_branch", "")
        log_review = ctx.run_dir / "review-implementation.review.log"
        log_addr = ctx.log_path(self.name)
        log_commit = ctx.run_dir / "review-implementation-commit-msg.log"

        if ctx.step_get(self.name, "verify_errors", None) is None:
            ctx.step_set(self.name, "verify_errors", "")

        with engine.stage(self.name) as s:
            # Phase A: invoke script once per step run
            if not ctx.step_get(self.name, "review_done", False):
                s.update("reviewing")
                argv = shlex.split(cfg["cmd"])
                argv[0] = _resolve_argv0(argv[0], ctx.get("repo"))
                env = {
                    **os.environ,
                    "DRAFT_REPO_DIR": wt_dir,
                    "DRAFT_BRANCH": branch,
                    "DRAFT_BASE_BRANCH": _short_base(base_branch),
                    "DRAFT_SPEC_FILE": spec_path,
                }
                verdict = _invoke_script(argv, wt_dir, env, cfg["timeout"], log_review)
                if verdict.kind == "infra_failure":
                    print(
                        f"review-implementation: review script failed ({verdict.reason});"
                        " proceeding without address loop",
                        file=sys.stderr,
                    )
                    ctx.step_set(self.name, "review_done", True)
                    ctx.step_set(self.name, "review_issues", "")
                    ctx.save()
                    return
                ctx.step_set(self.name, "review_done", True)
                ctx.step_set(self.name, "review_issues", verdict.stdout)
                ctx.save()

            review_issues = ctx.step_get(self.name, "review_issues", "")
            if not review_issues:
                return  # approval

            # Phase B: address loop
            impl_template = (
                files("draft.steps.review_implementation")
                .joinpath("review_implementation.md")
                .read_text()
            )
            suggest_template = (
                files("draft.steps.review_implementation")
                .joinpath("suggest_checks.md")
                .read_text()
                if cfg["suggest_extra_checks"]
                else None
            )
            verify_hook_entries = lifecycle.get_hooks(self.name, "verify")
            verify_commands = _render_verify_commands(verify_hook_entries)
            static_cmds = [
                e["cmd"]
                for e in verify_hook_entries
                if isinstance(e, dict) and e.get("cmd")
            ]
            spec_text = _read_spec_text(spec_path)

            for attempt in range(1, cfg["max_retries"] + 1):
                prefix = (
                    "" if attempt == 1 else f"attempt {attempt}/{cfg['max_retries']} — "
                )
                s.update(prefix + "addressing review")
                engine.run_llm(
                    prompt=_render_addr_prompt(
                        impl_template,
                        spec_text,
                        review_issues,
                        verify_commands,
                        ctx.step_get(self.name, "verify_errors", ""),
                    ),
                    cwd=wt_dir,
                    log_path=log_addr,
                    step_metrics=step_metrics,
                    allowed_tools=["Bash", "Edit", "Write", "Read"],
                    timeout=cfg["timeout"],
                )

                if not _has_changes(wt_dir):
                    if attempt == 1:
                        print(
                            "review-implementation: review feedback was processed but produced"
                            " no changes (all items judged out of scope or non-applicable)."
                            " Reviewer feedback follows:",
                            file=sys.stderr,
                        )
                        print(review_issues, file=sys.stderr)
                        ctx.step_set(self.name, "no_changes", True)
                        ctx.step_set(self.name, "verify_errors", "")
                        ctx.save()
                        return
                    ctx.step_set(self.name, "verify_errors", _NO_CHANGES_MSG)
                    ctx.save()
                    continue

                s.update(f"{prefix}verifying")
                failures = [
                    r for r in lifecycle.run_hooks(self.name, "verify") if r.rc != 0
                ]
                if failures:
                    ctx.step_set(
                        self.name,
                        "verify_errors",
                        "\n\n".join(f"$ {r.cmd}\n{r.output}" for r in failures),
                    )
                    ctx.save()
                    continue

                if cfg["suggest_extra_checks"]:
                    s.update(f"{prefix}suggesting checks")
                    suggested = _suggest_checks(
                        ctx,
                        engine,
                        step_metrics,
                        _SUGGESTER_CFG,
                        spec_text,
                        wt_dir,
                        static_cmds,
                        suggest_template,
                    )
                    ctx.step_set(self.name, "suggested_checks", suggested)
                    ctx.save()
                    s.update(f"{prefix}running suggested checks")
                    suggest_failures = _run_suggested_checks(
                        suggested, wt_dir, ctx.run_dir, engine, _SUGGESTER_CFG
                    )
                    if suggest_failures:
                        ctx.step_set(
                            self.name,
                            "verify_errors",
                            _format_suggested_failures(suggest_failures),
                        )
                        ctx.save()
                        continue

                s.update(f"{prefix}writing commit")
                message, used_fallback = _generate_commit_message(
                    review_issues,
                    spec_text,
                    wt_dir,
                    log_commit,
                    120,
                    3,
                    engine,
                    step_metrics,
                )
                _run_git_capture(["git", "add", "-A"], wt_dir, 60, log_commit)
                commit = _run_git_capture_allow_fail(
                    ["git", "commit", "-m", message], wt_dir, 60, log_commit
                )
                if commit.returncode != 0:
                    stdout_str = (
                        commit.stdout
                        if isinstance(commit.stdout, str)
                        else commit.stdout.decode("utf-8", errors="replace")
                    )
                    stderr_str = (
                        commit.stderr
                        if isinstance(commit.stderr, str)
                        else commit.stderr.decode("utf-8", errors="replace")
                    )
                    ctx.step_set(
                        self.name,
                        "verify_errors",
                        _format_pre_commit_errors(stdout_str, stderr_str),
                    )
                    ctx.save()
                    continue

                sha = _run_git_capture(
                    ["git", "rev-parse", "HEAD"], wt_dir, 30, log_commit
                ).strip()
                ctx.step_set(self.name, "commit_sha", sha)
                ctx.step_set(self.name, "commit_message_fallback", used_fallback)
                ctx.step_set(self.name, "verify_errors", "")
                if cfg["suggest_extra_checks"]:
                    ctx.step_set(self.name, "suggested_checks", [])
                ctx.save()
                return

            raise StepError(self.name, 1)
